---
title: "Portfolio"
author: "Yoji"
date: "10/6/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library(osmextract)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
library(tigris)
library(wesanderson)
library(tidytransit)
library(jpndistrict) 
library(osmdata)
library(stars)
library(tigris)
library(zonebuilder)
library(nngeo)

knitr::opts_chunk$set(warning = FALSE, message = FALSE, results=FALSE)
setwd("C:/Users/yojit/OneDrive - Harvard University/12.Spatial_Analysis_VIS2128/Spatial_Assignment_Portfolio/SA_Portfolio")
```

## 

```{r cars}
pubschool <- read_sf("https://github.com/cambridgegis/cambridgegis_data/raw/main/Landmark/Public_Schools/LANDMARK_PublicSchools.geojson")
prischool <- read_sf("https://github.com/cambridgegis/cambridgegis_data/raw/main/Landmark/Private_Schools/LANDMARK_PrivateSchools.geojson")
openspace_c <- read_sf("https://github.com/cambridgegis/cambridgegis_data/raw/main/Recreation/Open_Space/RECREATION_OpenSpace.geojson")
left_side  <- st_bbox(openspace_c)$xmin
top_side <- st_bbox(openspace_c)$ymax

ggplot(data = openspace_c) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "cartolight") +
  geom_sf(data = openspace_c, aes(color = OWNER, fill = OWNER)) +
  geom_sf(data = pubschool, size = 3, color = "seagreen1", alpha = 1/2) +
  geom_sf(data = prischool, size = 3, color = "tomato", alpha = 1/2) +
  annotate(geom = "text", x = left_side, 
           y = top_side, 
           label = paste("Location of Private and Public Schools and Their Proximity to Open Spaces"),
           hjust = 0, vjust = 0, size = 4) +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tr",
                         style = north_arrow_minimal()) +
  theme_void() +
  labs(caption = "Map tiles by OpenStreetMap")
```

## 
```{r pressure, echo=FALSE}
hospitals <- read_sf("https://bostonopendata-boston.opendata.arcgis.com/datasets/8f1e5741a4ee4c0f82925d17aab3c002_2.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D")
openspace <- read_sf("https://bostonopendata-boston.opendata.arcgis.com/datasets/2868d370c55d4d458d4ae2224ef8cddd_7.kml")
hydro <- read_sf("https://bostonopendata-boston.opendata.arcgis.com/datasets/2b3c0fa13b1c468eb702a3645fcc6bcb_5.kml")

hospitals <- hospitals %>% 
  st_transform(2249)
openspace <- openspace %>% 
  st_transform(2249)
hydro <- hydro %>% 
  st_transform(2249)


openspace_buffer <- st_buffer(openspace, dist = 100) %>% 
  st_union()

hospitals_openspace <- hospitals[openspace_buffer, ]

hospitals <- hospitals %>% 
  st_join(hospitals_openspace) %>% 
  mutate(by_openspace = !is.na(Name.y))

n_openspace_hospitals <- sum(hospitals$by_openspace)

n_hospitals <- length(hospitals$by_openspace)

pct_openspace_hospitals <- n_openspace_hospitals / n_hospitals * 100

openspace <- read_sf("openspace.geojson")

right_side <- st_bbox(openspace)$xmax
left_side  <- st_bbox(openspace)$xmin
top_side <- st_bbox(openspace)$ymax
bottom_side <- st_bbox(openspace)$ymin

ggplot(hydro) +
  geom_sf(fill = "cadetblue1", color = NA) +
  geom_sf(data = openspace, aes(fill = hospitals_dist)) +
  coord_sf(xlim = c(left_side, right_side),
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_c(name = "Boston Openspace \nby distance to a hospital") +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tr",
                         style = north_arrow_nautical()) +
  annotate(geom = "text", x = left_side + 300,
           y = top_side - 500,
           label = paste("On average, a Boston openspace\nis 1,458m from hospitals",
                         sep = ""),
           hjust = 0, vjust = 2, size = 3) +
  theme_map() +
  theme(legend.position = c(0.7, 0.05)) +
  theme(panel.background = element_rect(fill = "antiquewhite"),
        legend.background = element_rect(fill = alpha("white", 0.5), 
                                         color = "gray"))
```


```{r}
tokyo_streets <- read_sf("tokyo_streets.geojson")
iso_palette <- wes_palette("Darjeeling1", n = 5)
iso_tokyo_5min <-  read_sf("iso_tokyo_5min.geojson")
iso_tokyo_10min <-  read_sf("iso_tokyo_10min.geojson")
iso_tokyo_15min <-  read_sf("iso_tokyo_15min.geojson")

ggplot(tokyo_streets) +
  geom_sf(data = iso_tokyo_15min,
          aes(fill = "Area within 15 minutes"),
          color = NA) +
  geom_sf(data = iso_tokyo_10min,
          aes(fill = "Area within 10 minutes"),
          color = NA) +
  geom_sf(data = iso_tokyo_5min,
          aes(fill = "Area within 5 minutes"),
          color = NA) +
  geom_sf(alpha = 1/4) +
  scale_fill_manual(values = c(iso_palette[1],
                               iso_palette[2],
                               iso_palette[3]),
                    name = "Transit travel \ntime to the \nnearest museum\n(minutes)") +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tr", style = north_arrow_minimal()) +
  labs(caption = "Map tiles and data by OpenStreetMap") +
  theme_void() +
  theme(legend.background = element_rect(color = "NA"))
```


```{r}
transit_access <- read_sf("transit_access.geojson")

ggplot(transit_access) +
  geom_sf(aes(fill = accessibility), color = NA) +
  scale_fill_viridis_c(name = "Transit stops\nwithin 10-minutes\nwalk") +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tr", style = north_arrow_minimal()) +
  labs(caption = "Map tiles and data by OpenStreetMap") +
  theme_void()
```

```{r}
access_raster <- st_rasterize(transit_access["accessibility"], 
                              nx = 100, ny = 100) 

ggplot(tokyo_streets) +
  geom_stars(data = access_raster) +
  geom_sf(color = "white", alpha = 0.2) +
  scale_fill_viridis_c(na.value = NA, 
                       option="A",
                       name = "Walk access to\nbus stops") +
  labs(caption = "Map tiles and data by OpenStreetMap") +
  theme_void()
```

```{r}
access_contours <- st_contour(access_raster, contour_lines = TRUE, 
                              breaks = c(0,10,20,30,40))

ggplot(tokyo_streets) +
  geom_sf(color = "gray") +
  geom_sf(data = access_contours, aes(color = accessibility), fill = NA) +
  scale_color_viridis_c(na.value = NA, 
                       option="A",
                       breaks = c(0,10,20,30,40),
                       name = "Walk access to\nbus stops") +annotation_scale(location = "br") +
  annotation_north_arrow(location = "tr", style = north_arrow_minimal()) +
  labs(caption = "Map tiles and data by OpenStreetMap") +
  theme_void()
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```