---
title: "SA_Portfolio"
author: "Yoji"
date: "10/5/2021"
output: html_document
---

```{r setup, include=FALSE}
library(r5r)
library(osmextract)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
library(tigris)
library(wesanderson)
library(tidytransit)
library(jpndistrict) 
library(osmdata)
library(stars)

knitr::opts_chunk$set(warning = FALSE, message = FALSE, results=FALSE)
```

## R Markdown


```{r cars}
pubschool <- read_sf("https://github.com/cambridgegis/cambridgegis_data/raw/main/Landmark/Public_Schools/LANDMARK_PublicSchools.geojson")
prischool <- read_sf("https://github.com/cambridgegis/cambridgegis_data/raw/main/Landmark/Private_Schools/LANDMARK_PrivateSchools.geojson")
openspace <- read_sf("https://github.com/cambridgegis/cambridgegis_data/raw/main/Recreation/Open_Space/RECREATION_OpenSpace.geojson")

ggplot(data = openspace) +
    annotation_map_tile(zoomin = 0, progress = "none", type = "cartolight") +
    geom_sf(data = openspace, aes(fill = OWNER)) +
    geom_sf(data = pubschool, aes(color = "Public")) +
    geom_sf(data = prischool, aes(color = "Private")) +
    geom_sf(data = pubschool, size = 30, aes(color = "Public"), alpha = 1/15) +
    geom_sf(data = prischool, size = 30, aes(color = "Private"), alpha = 1/15)+
    scale_color_manual(values = c("Public" = "seagreen1", "Private" = "tomato", "Public" = "seagrean1", "Private" = "tomato"), name = "Quartermile") +
    theme_void() +
    labs(caption = "Map tiles by OpenStreetMap")
```

## Including Plots


```{r pressure, echo=FALSE}

```


